# This notebook extract the informations regarding the second election.

This step extracts tables from Yahoo finance, creates and renames csv, that are finally downloaded.

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Liste des URLs et noms correspondants
urls = {"https://finance.yahoo.com/quote/%5ETNX/history/?period1=1295827200&period2=1737710549" : "Taux10ans",}

# Fonction pour scraper un tableau sur une URL
def scrape_table_from_url(url):
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find('table')

    if table:
        rows = table.find_all('tr')
        data = []

        for row in rows:
            cols = row.find_all(['th', 'td'])
            cols = [col.text.strip() for col in cols]
            data.append(cols)

        # Création d'un DataFrame pandas
        df = pd.DataFrame(data)
        return df
    else:
        print(f"Aucun tableau trouvé pour l'URL : {url}")
        return None

# Scraper tous les tableaux des URLs
all_tables = {}

for url in urls:
    df = scrape_table_from_url(url)
    if df is not None:
        all_tables[url] = df




# Scraper les tableaux et ajouter la colonne à gauche
for url, name in urls.items():
    df = scrape_table_from_url(url)
    if df is not None:
        # Ajouter la colonne avec le nom du marché à gauche
        df.insert(0, "Indice", name)
        
        # Sauvegarde du DataFrame dans un fichier CSV avec le nom spécifique
        filename = f"{name}all_data.csv"
        df.to_csv(filename, index=False)
        print(f"Fichier CSV enregistré sous le nom : {filename}")

Fichier CSV enregistré sous le nom : Taux10ansall_data.csv

We transform the previously made CSV into pandas DataFrames

In [6]:

Taux10ans = pd.read_csv('Taux10ansall_data.csv')

In [7]:
# Suppression de la première ligne

Taux10ans = Taux10ans.iloc[1:]

In [8]:
months_translation = {
    'janv.': 'Jan', 'févr.': 'Feb', 'mars': 'Mar', 'avr.': 'Apr', 'mai': 'May', 'juin': 'Jun',
    'juil.': 'Jul', 'août': 'Aug', 'sept.': 'Sep', 'oct.': 'Oct', 'nov.': 'Nov', 'déc.': 'Dec'
}

# Remplacer les mois en français par les mois en anglais

Taux10ans['0'] = Taux10ans['0'].replace(months_translation, regex=True)

In [9]:
# Conversion en datetime

Taux10ans['0'] = pd.to_datetime(Taux10ans['0'], dayfirst=True)

Creating a list of DataFrames for merging each of them at once

In [10]:
# Liste des DataFrames déjà chargés
dfs = {
  
    "Taux10ans": Taux10ans,
    
}

In [11]:
from datetime import datetime

# Date de l'élection de Donald Trump
date_election = datetime(2012, 11, 5)

# Concaténer tous les DataFrames en un seul
final_df = pd.concat(dfs.values(), ignore_index=True)

In [12]:
final_df

         Indice          0       1       2       3       4       5  6
0     Taux10ans 2025-01-23  4.6380  4.6640  4.6170  4.6380  4.6380  -
1     Taux10ans 2025-01-22  4.5600  4.6170  4.5600  4.5990  4.5990  -
2     Taux10ans 2025-01-21  4.5740  4.5850  4.5520  4.5740  4.5740  -
3     Taux10ans 2025-01-17  4.5720  4.6250  4.5680  4.6090  4.6090  -
4     Taux10ans 2025-01-16  4.6840  4.6940  4.5880  4.6060  4.6060  -
...         ...        ...     ...     ...     ...     ...     ... ..
3516  Taux10ans 2011-01-28  3.4210  3.4530  3.3100  3.3290  3.3290  -
3517  Taux10ans 2011-01-27  3.4620  3.4620  3.3790  3.3850  3.3850  -
3518  Taux10ans 2011-01-26  3.3790  3.4420  3.3620  3.4280  3.4280  -
3519  Taux10ans 2011-01-25  3.3710  3.4200  3.3090  3.3190  3.3190  -
3520  Taux10ans 2011-01-24  3.4140  3.4320  3.3810  3.4080  3.4080  -

[3521 rows x 8 columns]

Indice                                                                                                                            object
Date                                                                                                                              object
Ouverture                                                                                                                         object
Plus haut                                                                                                                         object
Plus bas                                                                                                                          object
Fermer      Cours de clôture ajusté en fonction des fractionnements.                                                              object
Clôture ajustée      Cours de clôture ajusté pour les fractionnements et les distributions de dividendes et/ou de plus-values.    object
Volume                                                                                                                            object

dtype: object

In [13]:
final_df = final_df.rename(columns={'0' :'Date', '1':'Ouverture', '2' : 'Plus haut', '3' : 'Plus bas', '4' : 'Fermer', '5' : 'Cloture ajusté', '6' :'Volume'})

# Problème avec le mois qui contiennt des accents

Reseting the index to have the first row as column names.

We create a after/before the election variable

In [14]:

final_df['Avant_Apres_Election'] = final_df['Date'].apply(lambda x: 'Before' if x < date_election else 'After')

# Exporter vers un CSV consolidé
final_df.to_csv("indices_financiers_consolidesall.csv", index=False)
print("Le fichier CSV consolidé a été enregistré sous le nom : indices_financiers_consolides1.csv")

Le fichier CSV consolidé a été enregistré sous le nom : indices_financiers_consolides1.csv

In [15]:
final_df

,Indice,Date,Ouverture,Plus haut,Plus bas,Fermer,Cloture ajusté,Volume,Avant_Apres_Election
0,Taux10ans,2025-01-23,4.6380,4.6640,4.6170,4.6380,4.6380,-,After
1,Taux10ans,2025-01-22,4.5600,4.6170,4.5600,4.5990,4.5990,-,After
2,Taux10ans,2025-01-21,4.5740,4.5850,4.5520,4.5740,4.5740,-,After
3,Taux10ans,2025-01-17,4.5720,4.6250,4.5680,4.6090,4.6090,-,After
4,Taux10ans,2025-01-16,4.6840,4.6940,4.5880,4.6060,4.6060,-,After
...,...,...,...,...,...,...,...,...,...
3516,Taux10ans,2011-01-28,3.4210,3.4530,3.3100,3.3290,3.3290,-,Before
3517,Taux10ans,2011-01-27,3.4620,3.4620,3.3790,3.3850,3.3850,-,Before
3518,Taux10ans,2011-01-26,3.3790,3.4420,3.3620,3.4280,3.4280,-,Before
3519,Taux10ans,2011-01-25,3.3710,3.4200,3.3090,3.3190,3.3190,-,Before
3520,Taux10ans,2011-01-24,3.4140,3.4320,3.3810,3.4080,3.4080,-,Before

Some verifications

In [22]:
filtered_df_before_election = final_df[final_df['Avant_Apres_Election'] == 'Before']
filtered_df_before_election

,Indice,Date,Ouverture,Plus haut,Plus bas,Fermer,Cloture ajusté,Volume,Avant_Apres_Election
1334,CAC40,2016-11-04,"4 403,16","4 403,64","4 355,81","4 377,46","4 377,46",101 731 700,Before
1335,CAC40,2016-11-03,"4 402,79","4 456,21","4 399,29","4 411,68","4 411,68",101 390 600,Before
1336,CAC40,2016-11-02,"4 437,99","4 449,44","4 414,67","4 414,67","4 414,67",96 987 600,Before
1337,CAC40,2016-11-01,"4 532,34","4 537,99","4 460,54","4 470,28","4 470,28",79 346 900,Before
1338,CAC40,2016-10-31,"4 525,60","4 540,26","4 500,19","4 509,26","4 509,26",88 366 600,Before
...,...,...,...,...,...,...,...,...,...
13617,DowJ,2016-01-29,"15,957.00","16,376.00","15,937.00","16,356.00","16,356.00","217,260",Before
13618,DowJ,2016-01-28,"15,861.00","16,055.00","15,768.00","15,972.00","15,972.00","268,654",Before
13619,DowJ,2016-01-27,"15,999.00","16,151.00","15,789.00","15,851.00","15,851.00","261,837",Before
13620,DowJ,2016-01-26,"15,810.00","16,101.00","15,640.00","16,066.00","16,066.00","193,761",Before
13621,DowJ,2016-01-25,"16,008.00","16,039.00","15,790.00","15,811.00","15,811.00","179,722",Before

In [23]:
from datetime import datetime

# Définir la date pivot
date_pivot = datetime(2012, 11, 5)



# Filtrer les lignes avant la date pivot
filtered_df_before_pivot = final_df[final_df['Date'] < date_pivot]

# Affichage des premières lignes des données avant le 5th november 2024
print(filtered_df_before_pivot.head())

# Optionnel : Exporter vers un CSV si besoin
filtered_df_before_pivot.to_csv("avant_1_juillet_2024.csv", index=False)
print("Les données avant le 1er juillet 2024 ont été exportées dans avant_novembre_2012.csv")

     Indice       Date Ouverture Plus haut  Plus bas    Fermer Cloture ajusté  \
1334  CAC40 2016-11-04  4 403,16  4 403,64  4 355,81  4 377,46       4 377,46
1335  CAC40 2016-11-03  4 402,79  4 456,21  4 399,29  4 411,68       4 411,68
1336  CAC40 2016-11-02  4 437,99  4 449,44  4 414,67  4 414,67       4 414,67
1337  CAC40 2016-11-01  4 532,34  4 537,99  4 460,54  4 470,28       4 470,28
1338  CAC40 2016-10-31  4 525,60  4 540,26  4 500,19  4 509,26       4 509,26

           Volume Avant_Apres_Election
1334  101 731 700               Before
1335  101 390 600               Before
1336   96 987 600               Before
1337   79 346 900               Before
1338   88 366 600               Before
Les données avant le 1er juillet 2024 ont été exportées dans avant_1_juillet_2024.csv

In [24]:
filtered_df_before_pivot

,Indice,Date,Ouverture,Plus haut,Plus bas,Fermer,Cloture ajusté,Volume,Avant_Apres_Election
1334,CAC40,2016-11-04,"4 403,16","4 403,64","4 355,81","4 377,46","4 377,46",101 731 700,Before
1335,CAC40,2016-11-03,"4 402,79","4 456,21","4 399,29","4 411,68","4 411,68",101 390 600,Before
1336,CAC40,2016-11-02,"4 437,99","4 449,44","4 414,67","4 414,67","4 414,67",96 987 600,Before
1337,CAC40,2016-11-01,"4 532,34","4 537,99","4 460,54","4 470,28","4 470,28",79 346 900,Before
1338,CAC40,2016-10-31,"4 525,60","4 540,26","4 500,19","4 509,26","4 509,26",88 366 600,Before
...,...,...,...,...,...,...,...,...,...
13617,DowJ,2016-01-29,"15,957.00","16,376.00","15,937.00","16,356.00","16,356.00","217,260",Before
13618,DowJ,2016-01-28,"15,861.00","16,055.00","15,768.00","15,972.00","15,972.00","268,654",Before
13619,DowJ,2016-01-27,"15,999.00","16,151.00","15,789.00","15,851.00","15,851.00","261,837",Before
13620,DowJ,2016-01-26,"15,810.00","16,101.00","15,640.00","16,066.00","16,066.00","193,761",Before
13621,DowJ,2016-01-25,"16,008.00","16,039.00","15,790.00","15,811.00","15,811.00","179,722",Before

In [25]:
erreurs_dates = final_df[final_df['Date'].isna()]
print(erreurs_dates[['Date']].head(10))  # Affiche les 10 premières valeurs problématiques

Empty DataFrame
Columns: [Date]
Index: []

Creating new columns

In [26]:
final_df['Day_of_Week'] = final_df['Date'].dt.day_name()
final_df['Month'] = final_df['Date'].dt.month_name()

In [27]:
final_df['Is_Holiday_Period'] = final_df['Month'].apply(lambda x: 'yes' if x in ['November', 'December'] else 'no')

In [28]:
final_df

,Indice,Date,Ouverture,Plus haut,Plus bas,Fermer,Cloture ajusté,Volume,Avant_Apres_Election,Day_of_Week,Month,Is_Holiday_Period
0,CAC40,2022-01-21,"7 088,44","7 122,06","7 013,49","7 068,59","7 068,59",110 697 300,After,Friday,January,no
1,CAC40,2022-01-20,"7 190,02","7 199,97","7 123,62","7 194,16","7 194,16",76 932 800,After,Thursday,January,no
2,CAC40,2022-01-19,"7 104,11","7 211,24","7 104,11","7 172,98","7 172,98",84 173 800,After,Wednesday,January,no
3,CAC40,2022-01-18,"7 172,43","7 175,46","7 098,19","7 133,83","7 133,83",78 561 500,After,Tuesday,January,no
4,CAC40,2022-01-17,"7 167,53","7 213,70","7 148,98","7 201,64","7 201,64",53 465 300,After,Monday,January,no
...,...,...,...,...,...,...,...,...,...,...,...,...
13617,DowJ,2016-01-29,"15,957.00","16,376.00","15,937.00","16,356.00","16,356.00","217,260",Before,Friday,January,no
13618,DowJ,2016-01-28,"15,861.00","16,055.00","15,768.00","15,972.00","15,972.00","268,654",Before,Thursday,January,no
13619,DowJ,2016-01-27,"15,999.00","16,151.00","15,789.00","15,851.00","15,851.00","261,837",Before,Wednesday,January,no
13620,DowJ,2016-01-26,"15,810.00","16,101.00","15,640.00","16,066.00","16,066.00","193,761",Before,Tuesday,January,no
13621,DowJ,2016-01-25,"16,008.00","16,039.00","15,790.00","15,811.00","15,811.00","179,722",Before,Monday,January,no

Renaming the columns

In [29]:
print(final_df.columns.to_list())

['Indice', 'Date', 'Ouverture', 'Plus haut', 'Plus bas', 'Fermer', 'Cloture ajusté', 'Volume', 'Avant_Apres_Election', 'Day_of_Week', 'Month', 'Is_Holiday_Period']

In [30]:
final_df.rename(columns={
    'Taux10ans': 'Index',
    'Ouverture': 'Opening',
    'Plus haut': 'Highest',
    'Plus bas': 'Lowest',
    'Fermer      Cours de clôture ajusté en fonction des fractionnements.': 'Closure',
    'Clôture ajustée      Cours de clôture ajusté pour les fractionnements et les distributions de dividendes et/ou de plus-values.': 'Adjusted_Closure',
    'Avant_Apres_Election': 'Before_After_Election'
}, inplace=True)
final_df

,Indice,Date,Opening,Highest,Lowest,Fermer,Cloture ajusté,Volume,Before_After_Election,Day_of_Week,Month,Is_Holiday_Period
0,CAC40,2022-01-21,"7 088,44","7 122,06","7 013,49","7 068,59","7 068,59",110 697 300,After,Friday,January,no
1,CAC40,2022-01-20,"7 190,02","7 199,97","7 123,62","7 194,16","7 194,16",76 932 800,After,Thursday,January,no
2,CAC40,2022-01-19,"7 104,11","7 211,24","7 104,11","7 172,98","7 172,98",84 173 800,After,Wednesday,January,no
3,CAC40,2022-01-18,"7 172,43","7 175,46","7 098,19","7 133,83","7 133,83",78 561 500,After,Tuesday,January,no
4,CAC40,2022-01-17,"7 167,53","7 213,70","7 148,98","7 201,64","7 201,64",53 465 300,After,Monday,January,no
...,...,...,...,...,...,...,...,...,...,...,...,...
13617,DowJ,2016-01-29,"15,957.00","16,376.00","15,937.00","16,356.00","16,356.00","217,260",Before,Friday,January,no
13618,DowJ,2016-01-28,"15,861.00","16,055.00","15,768.00","15,972.00","15,972.00","268,654",Before,Thursday,January,no
13619,DowJ,2016-01-27,"15,999.00","16,151.00","15,789.00","15,851.00","15,851.00","261,837",Before,Wednesday,January,no
13620,DowJ,2016-01-26,"15,810.00","16,101.00","15,640.00","16,066.00","16,066.00","193,761",Before,Tuesday,January,no
13621,DowJ,2016-01-25,"16,008.00","16,039.00","15,790.00","15,811.00","15,811.00","179,722",Before,Monday,January,no

Downloading the final df

In [49]:
final_df.to_csv('df_trump2012all.csv')

In [31]:
election_date = pd.Timestamp('2012-11-05')

In [32]:
# Convertir la colonne "Date" au format datetime si ce n'est pas déjà fait
final_df['Date'] = pd.to_datetime(final_df['Date'])

In [34]:
import pandas as pd

# Définir la date de l'élection
election_date = pd.Timestamp('2012-11-05')

# Assurez-vous que la colonne "Date" est au format datetime
final_df['Date'] = pd.to_datetime(final_df['Date'])

# Filtrer les données pour "3 mois avant"
start_date_before = election_date - pd.DateOffset(months=3)
end_date_before = election_date - pd.DateOffset(days=1)

final_df_3m_before = final_df[(final_df['Date'] >= start_date_before) & (final_df['Date'] <= end_date_before)]
total_volume_3m_before = final_df_3m_before['Volume'].sum()

# Filtrer les données pour "3 mois après"
start_date_after = election_date + pd.DateOffset(days=1)
end_date_after = election_date + pd.DateOffset(months=3)

final_df_3m_after = final_df[(final_df['Date'] >= start_date_after) & (final_df['Date'] <= end_date_after)]
total_volume_3m_after = final_df_3m_after['Volume'].sum()

# Résultats
print("Total du volume 3 mois avant l'élection:", total_volume_3m_before)
print("Total du volume 3 mois après l'élection:", total_volume_3m_after)

Total du volume 3 mois avant l'élection: 101 731 700101 390 60096 987 60079 346 90088 366 60096 304 30099 701 50089 958 80091 091 90083 826 400104 200 10096 874 00083 323 60090 352 90069 410 30092 119 400106 795 50099 238 70098 600 20087 470 600117 429 400102 183 90098 277 70095 873 90061 707 600123 077 70080 427 60078 464 10091 773 80086 235 10084 998 800112 714 50082 277 50072 813 00080 744 000208 077 200102 309 100107 154 60091 945 60098 367 10090 844 40094 568 30075 442 80071 272 60075 716 900105 485 900107 456 600112 516 30075 965 20048 533 90071 774 70064 056 70066 667 60067 974 60065 669 90074 256 60062 662 60066 460 00075 577 60043 395 90062 472 70068 621 60068 145 50077 065 40070 007 00090 951 1003 841 910 0003 892 100 0004 289 120 0004 539 190 0003 926 560 0004 028 270 0004 209 400 0003 778 120 0003 756 200 0003 359 950 0003 456 390 0003 339 320 0003 364 990 0003 172 940 0002 832 440 0003 187 910 0003 538 030 0002 959 510 0003 393 060 0002 881 970 0003 578 770 0003 438 040 0003 883 710 0003 716 100 0003 113 850 0004 158 800 0004 215 620 0003 860 390 0003 414 090 0003 199 910 0003 289 860 0003 523 860 0003 685 450 0003 117 380 0003 141 820 0005 014 360 0003 373 720 0003 664 100 0004 141 670 0004 010 480 0004 233 960 0003 727 840 0003 319 420 0003 447 650 0003 091 120 0003 392 120 0003 766 390 0003 006 800 0002 654 780 0003 342 340 0002 969 310 0003 148 280 0003 041 490 0002 777 550 0003 084 800 0003 300 570 0003 388 910 0003 196 400 0003 078 530 0003 000 660 0003 423 160 0003 254 950 0003 334 300 0003 327 550 0003 663 070 000117330495856033827961422244152191141311315127261691142461 8932998686 10810 551482440237697204377379177353014465522521470543714158262551117197140135338621136661106205871 107------------------------------------------------------------------2 020 130 0002 113 730 0002 124 990 0001 880 920 0001 709 060 0001 911 810 0001 926 820 0001 732 300 0001 580 830 0001 533 370 0001 651 490 0001 745 270 0001 548 910 0001 476 970 0001 427 060 0001 593 610 0001 737 720 0001 567 930 0001 822 980 0001 365 600 0001 647 330 0001 655 480 0001 755 640 0001 711 810 0001 606 460 0002 063 260 0001 946 150 0001 788 240 0001 754 700 0001 672 190 0001 762 700 0001 914 550 0002 001 890 0001 697 530 0001 792 650 0003 013 860 0001 950 940 0001 902 680 0002 071 460 0002 007 610 0002 208 690 0001 839 790 0001 878 460 0001 777 940 0001 474 200 0001 592 520 0001 761 770 0001 561 020 0001 416 640 0001 591 060 0001 511 890 0001 714 780 0001 547 050 0001 560 210 0001 632 740 0001 659 080 0001 747 890 0001 698 390 0001 533 170 0001 501 620 0001 511 670 0001 651 240 0001 664 320 0001 624 450 0002 017 720 000134 800 000135 200 000123 000 000157 200 000167 900 000107 600 00098 100 000108 400 00087 700 000114 200 000112 400 000101 700 00098 600 00095 100 000109 400 000111 100 000116 300 000111 600 000100 300 000110 600 000115 100 000100 300 00099 200 000124 400 000122 700 000112 200 000157 100 000102 900 000138 000 000191 100 000121 500 000127 100 000117 800 000116 300 00098 200 000112 800 000123 900 000111 300 000132 500 000108 300 000127 400 000116 200 000131 500 000150 300 000103 700 000113 900 000104 600 00092 900 00091 100 000107 600 00095 300 000121 900 000130 400 000117 400 000110 000 00083 700 000119 100 000113 800 000127 500 000141 600 000129 400 0001 336 0511 078 6861 480 5691 469 5911 087 2011 390 4791 582 2651 048 7541 041 362807 829746 9581 068 248970 1741 116 022838 4561 219 2831 124 5961 217 1961 116 0081 494 0951 299 0551 209 5151 402 205775 0291 671 0481 165 9881 073 8971 172 225828 179719 7731 077 1001 115 10712 4746 9283 16212 25038 70331 2557 41125 62023 80857 77846 67751 220191 897256 770986 1431 642 2292 759 0592 063 6031 300 9761 052 529946 754987 238884 8071 112 0061 459 939779 5931 188 0341 001 8791 027 376924 123978 7921 315 208-----------------------------------------------------------------196,117155,396200,698228,082133,450278,900181,633186,078125,524111,904144,869156,282108,311120,223137,630170,631185,060146,994190,865191,030130,210137,416207,369121,065166,300194,374155,607153,632128,492104,660128,681189,572111,843122,943149,88726,69545,82384,678104,086178,683149,567104,364124,962158,496169,678132,594114,677105,443193,964116,870111,882110,672141,866112,21592,435127,972103,47280,67890,678111,15696,00587,30284,638122,773
Total du volume 3 mois après l'élection: 80 815 70098 607 30097 905 70098 487 80083 384 60079 429 00094 017 900114 294 30087 954 00078 546 600117 756 80095 638 90088 911 50087 737 00071 928 500106 285 90099 417 20099 652 70092 809 30072 709 60073 709 00088 092 00077 276 80082 609 50034 310 40053 055 00045 150 10049 371 20035 125 70048 362 60065 716 20066 626 60087 772 70094 842 000206 338 400141 188 300109 393 800110 469 00098 372 500121 620 200149 634 900141 483 500122 977 200111 540 300102 067 200111 644 600143 644 10089 267 60082 981 50064 855 70057 005 200102 199 800125 792 60084 146 400106 645 00088 436 200102 195 100112 077 800132 886 300121 053 300225 207 100204 613 400112 800 50089 701 7003 605 970 0003 809 760 0003 919 190 0004 089 730 0003 595 040 0003 137 420 0003 611 510 0003 849 340 0003 816 950 0003 155 240 0003 536 850 0003 168 390 0003 317 670 0003 586 950 0003 090 680 0003 466 220 0003 625 080 0003 640 560 0003 219 730 0003 342 080 0003 785 080 0003 768 890 0003 773 010 0002 671 550 0002 338 700 0002 402 750 0001 989 730 0002 021 230 0002 880 670 0002 854 880 0003 306 250 0003 252 840 0005 928 980 0004 173 360 0004 409 670 0003 875 630 0004 038 850 0003 886 460 0004 203 270 0004 504 070 0003 857 290 0003 898 530 0003 782 370 0005 067 470 0005 538 400 0003 709 190 0003 515 100 0001 584 590 0003 419 850 0003 960 520 0003 611 500 0003 580 900 0003 811 730 0003 847 900 0004 548 110 0005 373 670 0004 993 990 0006 458 450 0006 267 590 0003 921 850 0003 739 720 0008651 5121 1453 21250 503234 3521940324163826114796511020862165003652169501 570847010450462491462444876373313653221826523581 5211 5887 15842 124189 9141430919196071 1396620216631085034-----------------------------------------------------------------1 792 330 0002 077 010 0002 239 570 0002 047 460 0001 782 380 0001 669 190 0001 837 020 0001 964 040 0001 808 560 0001 652 370 0001 750 340 0001 809 900 0001 686 260 0001 759 440 0001 611 260 0001 805 840 0001 960 830 0001 798 610 0001 887 740 0001 711 870 0001 799 170 0001 885 490 0001 887 670 0001 551 690 0001 266 350 0001 326 660 0001 219 050 0001 144 900 0001 585 470 0001 496 850 0001 679 630 0001 688 680 0003 281 480 0002 101 320 0001 976 570 0002 094 860 0001 931 840 0002 042 340 0002 236 580 0002 125 370 0001 977 480 0001 800 570 0001 851 030 0002 269 790 0002 056 060 0001 791 760 0001 630 150 000768 080 0001 617 700 0001 890 410 0001 748 170 0001 865 770 0002 084 710 0002 066 130 0002 159 180 0002 371 900 0002 290 080 0002 986 760 0002 827 570 0001 739 440 0001 916 620 000140 900 000136 500 000131 500 000133 900 00097 800 000134 600 000145 200 000125 400 000131 500 000124 800 000125 800 000170 600 000119 100 000119 100 000119 100 000119 100 000119 100 000119 100 000119 100 000119 100 000134 500 000163 500 000117 800 000163 500 00077 700 000110 200 00085 500 000113 500 000130 300 000119 600 000106 000 000148 700 000154 600 000133 200 000147 600 000200 600 000212 300 000187 400 000151 700 000158 800 000134 500 000197 200 000188 000 000164 700 000125 600 000145 000 000164 900 000149 400 000121 900 000135 700 000166 800 000161 100 000200 300 000173 200 000165 300 000241 800 000229 400 000274 900 000100 000 000113 000 0001 887 9581 373 9581 496 4412 121 5001 214 6401 076 8941 392 9761 407 1131 168 4621 684 1651 461 7391 809 5711 290 8961 592 4291 584 2051 409 1841 460 875907 696889 3691 540 2291 882 8431 153 5151 442 195786 367766 254624 846263 382287 288585 524510 26511 59210 00711 3757 7713 3375 8618 54418 86817 05917 02252 88242 43392 573361 2061 214 6892 507 9381 479 1963 075 1042 263 8261 635 9731 914 2681 606 2221 843 3041 750 6962 439 4603 054 8704 231 8341 036 202788 423-------------------------------------------------------------132,981130,390133,901149,470148,33577,803109,273123,956121,989129,845150,968119,383121,032140,71699,768151,822185,272110,88585,834121,917108,860104,361151,885109,47586,35388,82945,57742,11371,70664,39781,80087,037129,98441,65852,32055,55668,74971,100192,372164,281103,826141,710136,560186,012162,273119,176128,39984,532120,477115,567112,690113,076119,808129,349146,311212,519339,145651,872162,218172,027

In [35]:
final_df_3m_after

,Indice,Date,Opening,Highest,Lowest,Fermer,Cloture ajusté,Volume,Before_After_Election,Day_of_Week,Month,Is_Holiday_Period
1270,CAC40,2017-02-03,"4 808,46","4 847,47","4 803,91","4 825,42","4 825,42",80 815 700,After,Friday,February,no
1271,CAC40,2017-02-02,"4 785,14","4 812,31","4 774,18","4 794,29","4 794,29",98 607 300,After,Thursday,February,no
1272,CAC40,2017-02-01,"4 786,85","4 823,81","4 782,61","4 794,58","4 794,58",97 905 700,After,Wednesday,February,no
1273,CAC40,2017-01-31,"4 790,28","4 812,55","4 748,90","4 748,90","4 748,90",98 487 800,After,Tuesday,January,no
1274,CAC40,2017-01-30,"4 823,50","4 830,69","4 771,98","4 784,64","4 784,64",83 384 600,After,Monday,January,no
...,...,...,...,...,...,...,...,...,...,...,...,...
13418,DowJ,2016-11-14,"18,806.00","18,918.00","18,762.00","18,822.00","18,822.00","212,519",After,Monday,November,yes
13419,DowJ,2016-11-10,"18,533.00","18,821.00","18,492.00","18,786.00","18,786.00","339,145",After,Thursday,November,yes
13420,DowJ,2016-11-09,"18,304.00","18,590.00","17,418.00","18,532.00","18,532.00","651,872",After,Wednesday,November,yes
13421,DowJ,2016-11-08,"18,188.00","18,345.00","18,129.00","18,285.00","18,285.00","162,218",After,Tuesday,November,yes
13422,DowJ,2016-11-07,"18,000.00","18,209.00","17,983.00","18,192.00","18,192.00","172,027",After,Monday,November,yes

In [36]:
final_df_3m_before

,Indice,Date,Opening,Highest,Lowest,Fermer,Cloture ajusté,Volume,Before_After_Election,Day_of_Week,Month,Is_Holiday_Period
1334,CAC40,2016-11-04,"4 403,16","4 403,64","4 355,81","4 377,46","4 377,46",101 731 700,Before,Friday,November,yes
1335,CAC40,2016-11-03,"4 402,79","4 456,21","4 399,29","4 411,68","4 411,68",101 390 600,Before,Thursday,November,yes
1336,CAC40,2016-11-02,"4 437,99","4 449,44","4 414,67","4 414,67","4 414,67",96 987 600,Before,Wednesday,November,yes
1337,CAC40,2016-11-01,"4 532,34","4 537,99","4 460,54","4 470,28","4 470,28",79 346 900,Before,Tuesday,November,yes
1338,CAC40,2016-10-31,"4 525,60","4 540,26","4 500,19","4 509,26","4 509,26",88 366 600,Before,Monday,October,no
...,...,...,...,...,...,...,...,...,...,...,...,...
13482,DowJ,2016-08-11,"18,450.00","18,594.00","18,433.00","18,565.00","18,565.00","111,156",Before,Thursday,August,no
13483,DowJ,2016-08-10,"18,470.00","18,513.00","18,417.00","18,452.00","18,452.00","96,005",Before,Wednesday,August,no
13484,DowJ,2016-08-09,"18,466.00","18,522.00","18,442.00","18,466.00","18,466.00","87,302",Before,Tuesday,August,no
13485,DowJ,2016-08-08,"18,458.00","18,508.00","18,436.00","18,460.00","18,460.00","84,638",Before,Monday,August,no
13486,DowJ,2016-08-05,"18,275.00","18,474.00","18,273.00","18,454.00","18,454.00","122,773",Before,Friday,August,no

In [ ]:
final_df_3m_before.to_csv('Trump_2016_prior')
final_df_3m_before.to_csv('Trump_2016_after')